USE [PlanPiso]
GO

/****** Object:  View [dbo].[VEHICULODESCRIPCION_VIEW]    Script Date: 02/12/2018 18:12:01 ******/
IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[VEHICULODESCRIPCION_VIEW]'))
DROP VIEW [dbo].[VEHICULODESCRIPCION_VIEW]
GO

USE [PlanPiso]
GO

/****** Object:  View [dbo].[VEHICULODESCRIPCION_VIEW]    Script Date: 02/12/2018 18:12:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VEHICULODESCRIPCION_VIEW] AS
SELECT 
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'SUZUKI',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAAU_Cuautitlan].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAAU_Concentra].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 1

UNION

SELECT 
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'SUZUKI',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAAU_Pedregal].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAAU_Concentra].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 2

UNION

SELECT 
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'SUZUKI',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAAU_Universidad].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAAU_Concentra].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 3

UNION

SELECT 
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'PEUGEOT',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAAT_Peugeot].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAAT_Concentra].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 4

UNION

SELECT 
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'HONDA',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAHondaZaragoza].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAHondaConcen].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 5

UNION

SELECT
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'NISSAN',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAZM_Zaragoza].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAZM_Concentra].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 6

UNION

SELECT
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'NISSAN',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAZM_Abasto].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAZM_Concentra].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 7

UNION

SELECT 
	[idEmpresa],	
	[idSucursal],	
	[CCP_IDDOCTO],
	[MARCA] = 'NISSAN',
	[VEH_NUMSERIE],	
	[VEH_TIPOAUTO],	
	[VEH_NOMOTOR],
	[VEH_FECVENTA],	
	[VEH_ANMODELO],	
	[VEH_CATALOGO],
	[VEH_FECHOPE],
	[VEH_NOFACTPLAN],
	[VEH_IMPFACTPLAN],
	[VEH_SITUACION],
	[VEH_COLOEXTE],
	[VEH_QCTRANSMISION],
	[UNC_TIPO]
FROM VINDOCUMENTOS_VIEW VIS
INNER JOIN [192.168.20.92].[GAZM_FAerea].[dbo].[SER_VEHICULO] VEH ON VIS.VIN = VEH.VEH_NUMSERIE COLLATE Modern_Spanish_CI_AS
LEFT JOIN [192.168.20.92].[GAZM_Concentra].[dbo].[uni_catalogo] CAT ON CAT.UNC_IDCATALOGO = VEH.VEH_CATALOGO AND CAT.UNC_MODELO = VEH.VEH_ANMODELO
WHERE idSucursal = 8

GO


